server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:whattocook
    username: sa
    password:
    driverClassName: org.h2.Driver
  data:
    rest:
      base-path: /api/v1
  security:
    user:
      password: user

logging:
  level:
    root: DEBUG