# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      UPSTREAM: git@github.com:babyygemperor/test-repo.git

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: Set up remote
        run: git remote add upstream ${{env.UPSTREAM}}
        
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.PRIVATE_KEY }}
        
      - name: Copy ssh public_key
        run: echo "${{SECRETS.PUBLIC_KEY}}" > ~/.ssh/id_rsa.pub
        
      - name: Pull upstream
        run: git fetch --unshallow
        
      - name: Git push to other repo
        run: git push upstream
